---
title: "40-explore-analysis"
output: html_notebook
---



```{r}
USvideos_NNA %>%
  ggplot()+
  geom_density(aes(x=views, y=stat(density)),fill="#F7000B", color=NA, alpha=0.7) +
  theme_minimal() +
  theme(
    panel.grid = element_blank()
  ) +
  scale_x_log10(labels = comma) +
  labs(x = "View Count")
```

```{r}
USvideos_NNA %>%
  ggplot()+
  #geom_histogram(aes(x=views, y=stat(density)),binwidth=0.1) +
  geom_density(aes(x=likes, y=stat(density)),fill="#F7000B", color=NA,alpha=0.7) +
  geom_density(aes(x=dislikes, y=stat(density)),fill="black", color=NA,alpha=0.7) +
  scale_x_log10(labels = comma) +
  theme_minimal() +
  theme(
    panel.grid = element_blank()
  )+
  labs(x = "Like and Dislike Count")
```
```{r}
USvideos_NNA %>%
  ggplot()+
  geom_density(aes(x=comment_count, y=stat(density)),fill="#F7000B", color=NA, alpha=0.7) +
  theme_minimal() +
  theme(
    panel.grid = element_blank()
  ) +
  scale_x_log10(labels = comma) 
```



```{r}
USvideos_NNA %>%
  mutate(category_id=as.character(category_id)) %>%
  group_by(category_id) %>%
  mutate(num=n()) %>%
  ungroup() %>% 
  ggplot() +
  geom_col(aes(x=category_id, y=num),fill="#F7000B") +
  geom_jitter(aes(x= category_id, y= views),size=0.2,color="black",width = 0.25) +
  theme_minimal() +
  theme(
    panel.grid = element_blank()
  ) +
  scale_x_discrete(labels = c("Film & Animation", "Music", "Pets & Animals", "Sports", "Travel & Events", "Autos & Vehicles", "Gaming", "People & Blogs", "Comedy", "Entertainment", "News & Politics", "Howto & Style", "Education","Science & Technology","Nonprofit", "Shows"))+
  scale_y_continuous(labels = comma)+
  coord_flip()

```




```{r}
USvideos_NNA %>%
  mutate(weekday_num=case_when(weekday=="Monday" ~ 1,
                               weekday=="Tuesday" ~ 2,
                               weekday=="Wednesday" ~ 3,
                               weekday=="Thursday" ~ 4,
                               weekday=="Friday" ~ 5,
                               weekday=="Saturday" ~ 6,
                               weekday=="Sunday" ~ 7)) %>%
  mutate(weekday_num=as.factor(weekday_num)) %>%
  group_by(weekday_num) %>%
  mutate(num=n()) %>%
  ggplot(aes(x=weekday_num)) +
  geom_col(aes(y=num),fill="#F7000B") +
  geom_jitter(aes(y= views),size=0.2,color="black") +
  theme_minimal() +
  theme(
    panel.grid = element_blank()
  )+
  scale_y_continuous(labels = comma)+
  scale_x_discrete(labels=c("Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"))+
  coord_flip()

```




```{r}
USvideos_NNA %>%
  mutate(time_month=as.factor(time_month)) %>%
  group_by(time_month) %>%
  arrange(time_month) %>% 
  mutate(num=n()) %>%
  ggplot() +
  geom_col(aes(x=time_month, y=num),fill="#F7000B") +
  geom_jitter(aes(x= time_month, y= views),size=0.2, alpha=0.7,width = 0.3) +
  theme_minimal() +
  theme(
    panel.grid = element_blank()
  )+
  scale_y_continuous(labels = comma) +
  scale_x_discrete(labels = c("Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec")) +
  coord_flip()

```




```{r}
USvideos_NNA %>%
  mutate(time_hour=as.factor(time_hour)) %>%
  group_by(time_hour) %>%
  mutate(num=n()) %>%
  ggplot() +
  #geom_jitter(aes(x= time_hour, y= views),size=0.2,alpha=0.7) +
  geom_col(aes(x=time_hour, y=num),fill="#F7000B") +  
  scale_y_continuous(labels = comma)+
  scale_x_discrete(labels = c(19,20,21,22,23,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18)) +
  theme_minimal() +
  theme(
    panel.grid = element_blank()
  )
```

```{r}
USvideos_NNA %>%
  mutate(time_hour=as.factor(time_hour)) %>%
  ggplot()+
  geom_jitter(aes(x= time_hour, y= views),size=0.2, alpha=0.7) +
  scale_y_continuous(labels = comma)+
  scale_x_discrete(labels = c(19,20,21,22,23,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18)) +


  theme_minimal() +
  theme(
    panel.grid = element_blank()
  )
```

```{r}
USvideos_NNA %>%
  group_by(chr_row_num) %>%
  mutate(num=n()) %>%
  ggplot()+
  geom_line(aes(x=chr_row_num,y=num),size=1,color="#F7000B") +
    scale_x_log10()+

  # geom_smooth(aes(x=chr_row_num,y=num),color="#F7000B") +
  theme_minimal() +
  theme(
    panel.grid = element_blank()
  )
```

```{r}
USvideos_NNA %>%
  filter(chr_row_num<200) %>%
  ggplot() +
  geom_jitter(aes(x=chr_row_num,y=views), size=0.25, alpha=0.7,width = 0.03) +
  scale_y_continuous(labels = comma)+
  scale_x_log10()+

  theme_minimal() +
  theme(
    panel.grid = element_blank()
  )
```

```{r}
USvideos_NNA %>%
  group_by(pattern_num) %>%
  mutate(num=n()) %>%
  ggplot()+
  geom_line(aes(x=pattern_num,y=num),size=1,color="#F7000B") +
  geom_smooth(aes(x=pattern_num,y=num), color="#F7000B", method = "loess") +
  theme_minimal() +
  theme(
    panel.grid = element_blank()
  )
```

```{r}
USvideos_NNA %>%
  ggplot() +
  geom_jitter(aes(x=pattern_num,y=views), size=0.25, alpha=0.7) +
  scale_y_continuous(labels = comma)+

  theme_minimal() +
  theme(
    panel.grid = element_blank()
  )
```

```{r}
USvideos_NNA %>%
  group_by(chr_length) %>%
  mutate(num=n()) %>%
  ggplot()+
  geom_line(aes(x=chr_length,y=num))  +
  geom_smooth(aes(x=chr_length,y=num), color="#F7000B", size=1.5)  +
  theme_minimal() +
  theme(
    panel.grid = element_blank()
  )
```


```{r}
USvideos_NNA %>%
  ggplot() +
  geom_jitter(aes(x=chr_length,y=views), size=0.25,alpha=0.7) +
  scale_y_continuous(labels = comma)+

  theme_minimal() +
  theme(
    panel.grid = element_blank()
  )
```

```{r}
USvideos_NNA %>%
  group_by(chr_upper_num) %>%
  mutate(num=n()) %>%
  ggplot()+
  geom_line(aes(x=chr_upper_num,y=num),color="#F7000B",size=1) +
  theme_minimal() +
  theme(
    panel.grid = element_blank()
  )
```

```{r}
USvideos_NNA %>%
  ggplot() +
  geom_jitter(aes(x=chr_upper_num,y=views), size=0.25, alpha=0.7) +
  scale_y_continuous(labels = comma)+

  theme_minimal() +
  theme(
    panel.grid = element_blank()
  )
```


```{r}
USvideos_NNA %>%
  ggplot()+
  geom_jitter(aes(x=likes_rate, y= views),size=0.25, alpha=0.5, width = 0.05)+
  scale_y_continuous(labels = comma)+

  scale_x_log10(labels = comma) +
  theme_minimal() +
  theme(
    panel.grid = element_blank()
  )
```

```{r}
new_word <- str_to_lower(USvideos_NNA$title)
new_word <- str_split(new_word, "[^a-z]")
words <- unlist(new_word)
# words <- case_when(words == "br" ~ "bedroom",
#                    words == "apt" ~ "apartment",
#                    TRUE ~ words)
words <- as.data.frame(words)
```

